#!/bin/bash

# Küsime kasutajalt suvalist täisarvu
read -p "Sisesta suvaline täisarv: " number

# Arvutame numbrite summa
summa=0
for (( i=0; i<${#number}; i++ )); do
    digit=${number:$i:1}
    if [[ $digit =~ [0-9] ]]; then
        summa=$((summa + digit))
    fi
done

# Väljastame tulemuse
echo "Arvu $number numbrite summa on $summa"
