#!/bin/bash
# Skript bussiekskursioonide korraldajale, mis arvutab täielikult täidetud busside arvu ja maha jäänud inimeste arvu.

echo -n "Sisesta reisijate arv: "
read reisijad

echo -n "Sisesta bussi kohtade arv: "
read kohad

# Arvutame täielikult täidetud busside arvu ja maha jäänud inimeste arvu.
taitetud=$((reisijad / kohad))
mahajaanud=$((reisijad % kohad))

echo "Täielikult täidetud busside arv: $taitetud"
echo "Maha jäänud inimeste arv: $mahajaanud"
